baseURL = 'https://mrants.co.uk'
languageCode = 'en-gb'
title = 'Mr Ant&#39;s Bar'

[params]
  Logo = 'img/logo.png'

[[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 10

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'